-- DATABASE CREATION
CREATE DATABASE IF NOT EXISTS alx_book_store;

-- SELECT DATABASE TO USE
USE alx_book_store;

-- 1. AUTHORS Table
CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(215) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);

-- 2. BOOKS Table
CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- 3. CUSTOMERS Table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL UNIQUE,
    ADDRESS TEXT,
    PRIMARY KEY (CUSTOMER_ID)
);

-- 4. ORDERS Table
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- 5. ORDER_DETAILS Table
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERDETAILID INT NOT NULL AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    PRIMARY KEY (ORDERDETAILID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
